### PR TITLE
Recurring payments over REST API

### PR DESCRIPTION
**Pull request by tiredenzo**
Hello this is a PR for recurring payments.
I did not really understand what kind of unitary test i had to make
I only did funtional

### CODE REVIEW

**Comment by tiredenzo** [comment]
Sorry this is my first PR :) but
rake:test passes i never dealt with travis CI before i'm looking what is happening

**Comment by wvanbergen** [comment]
Yeah, that error is OK. The integration tests are very flaky on the CI, probably due to fraud filters or something on Adyen's servers. Don't worry about it.

**Comment by tiredenzo** [comment]
ok cool, if this PR is accepted i'd love to be in contributors list as this is my first open source contribution :+1: 
I will work on IDEAL beginning / middle of february :)

**Comment by wvanbergen** [comment]
I will look at it tonight, and add you to the list.

**Comment by wvanbergen** [comment]
There you go: https://github.com/wvanbergen/adyen/commit/00864d33487b84aaf710365abdb36816c6dde6b7

Looking forward to your IDEAL changes.

**Comment by tiredenzo** [comment]
Super bedankt!

**Comment by tiredenzo** [comment]
My IDEAL integration was painless
`````
  def setup_authorization
    obj = Adyen::Form.flat_payment_parameters(
      skin: :default,
      currency_code: order.currency.upcase,
      payment_amount: total_with_currency,
      merchant_reference: order.reference,
      ship_before_date: (order.campaign.until + 15.days).strftime('%F'),
      session_validity: (Time.now.utc + 30*60).strftime('%FT%TZ'),
      brand_code: 'ideal',
      country_code: 'NL',
      shopper_locale: order.locale,
      shopper: {
        first_name: order.first_name,
        last_name: order.last_name,
      }
      )
    { url: Adyen::Form.url(nil, 'details'), form_data: obj }
  end
`````

There is nothing to change for me so no PR are needed

**Comment by wvanbergen** [comment]
Cool!

**Pull request merged**
