### PR TITLE
Support addition data of Boletos

### PR DESCRIPTION
**Pull request by tinogomes**
Adding attributes to `BilletResponse#params`: `barcode`, `due_date`, `expiration_date`

### CODE REVIEW

**Comment by mvz** [comment]
LGTM. @wvanbergen wdyt?

**Comment by wvanbergen** [comment]
This PR needs rebasing, but fine to merge afterwards :+1:

**Comment by mvz** [comment]
@tinogomes can you rebase on current master please to resolve the merge conflicts?

**Comment by tinogomes** [comment]
@wvanbergen @mvz rebased with master!

**Comment by mvz** [comment]
Thanks, @tinogomes.

**Pull request merged**
