### PR TITLE
merge installments param - one click payment call

### PR DESCRIPTION
**Pull request by rinaldifonseca**
Adyen accepts the installments param in the one click payment like in the default payment

### CODE REVIEW

**Comment by wvanbergen** [comment]
I'm no longer maintaining the soap API. Can you implement this using the
the REST API instead?

**Comment by rinaldifonseca** [comment]
Hi @wvanbergen 

Is your objective to move completely from SOAP to the REST implementation? How long the SOAP implementation will live in the project?(because I imagine that both versions will coexist awhile)

Thanks

**Comment by wvanbergen** [comment]
The project will remove to the REST API completely. The SOAP API is deprecated and at some point will be removed, but not anytime soon. I am not maintaining it anymore though.

**Comment by wvanbergen** [comment]
For more information on why the SOAP API is deprecated, see https://github.com/wvanbergen/adyen/issues/106#issuecomment-68834726

**Comment by rinaldifonseca** [comment]
Ok, I will write a rest version.

**Comment by rinaldifonseca** [comment]
Hi @wvanbergen, I sent a new one

**Comment by wvanbergen** [comment]
Thanks. I will close this PR.

**Pull request closed without merging**
