### PR TITLE
Making HMAC Signature generic

### PR DESCRIPTION
**Pull request by lucasgomide**
About #134, I did a generic class for hmac signature. To sign notifications responses  when use Adyen API.

But, I'm not sure if the 'new' documentation it's rigth..

### CODE REVIEW

**Comment by lucasgomide** [comment]
@wvanbergen can you retry that's build on travis, please
https://travis-ci.org/wvanbergen/adyen/builds/127092771

**Comment by wvanbergen** [comment]
cc @mvz

**Comment by wvanbergen** [comment]
@lucasgomide can you rebase on master instead? I think that should fix it.

**Comment by lucasgomide** [comment]
done

**Comment by wvanbergen** [comment]
This looks OK to me, but I'll let @mvz look at this before merging.

**Comment by mvz** [comment]
Maybe I'm missing something, but what is `Adyen::REST::Signature` for?

**Comment by lucasgomide** [comment]
I'm using Adyen API REST, and I enabled HMAC Verification on my CA. But this gem haven't support for this.

This PR make a generic Signature HMAC. For HPP and REST.

Now services as HPP or REST can verify signature. Understand ?

**Comment by lucasgomide** [comment]
I created `Adyen::REST::Signature` and `Adyen::HPP::Signature` because the fields to verify are differents

**Comment by lucasgomide** [comment]
#134 thread original

**Comment by mvz** [comment]
Thanks @lucasgomide. Looks good to me then.

**Comment by lucasgomide** [comment]
nice @mvz !

So @wvanbergen or @mvz, can you merge it ?

**Comment by mvz** [comment]
I think @wvanbergen and I are in agreement, so I'm going to merge this.

**Pull request merged**
