### PR TITLE
Replace Adyen::Form with Adyen::HPP

### PR DESCRIPTION
**Pull request by wvanbergen**

### CODE REVIEW

**Comment by trekdemo** [comment]
@wvanbergen what is the status of this? Do you still working on it?

**Comment by wvanbergen** [comment]
This is low priority for me right now.

**Comment by prognostikos** [comment]
@wvanbergen I'm willing to take a crack at this as part of #118 if it makes sense - would just like a description of your general thoughts on the new architecture.

**Comment by wvanbergen** [comment]
The main thing I'd like to change is to move from a singleton module (`module Adyen::Form`), to a class that you can instantiate (`class Adyen::HPP`). This allows you to use multiple configurations in the same app without weird hacks. I made a similar change for `Adyen::REST`.

**Comment by arnoutdemooij** [comment]
@wvanbergen 
I added a pull request for the HPP branch, with a partial implementation of `Adyen::HPP` (including `Client`, `Request` and `Response` classes). The `HPP` module uses the SHA-256 HMAC signature calculation that @prognostikos added earlier.
One can still use the unchanged `Adyen::Form` module for the 'deprecated' SHA-1 calculation.

**Comment by aponsin** [comment]
I would love to see this merged.

**Comment by wvanbergen** [comment]
@mvz Any work remaining on this?

**Comment by mvz** [comment]
I don't think so, but I'm trying it out now.

**Comment by arnoutdemooij** [comment]
For issue #118, some comments were made about [slicing parameters](https://github.com/wvanbergen/adyen/issues/118#issuecomment-150413930), [taking care of special characters in the merchant signature](https://github.com/wvanbergen/adyen/issues/118#issuecomment-152885696) and [optionally using a special form_tag helper to prevent Rails from adding it's own parameters to a request to Adyen](https://github.com/wvanbergen/adyen/issues/118#issuecomment-153011948).

**Comment by mvz** [comment]
* It is safer to do parameter slicing client-side, since the Adyen result may include additional parameters (e.g., brand code).
* Are we sure the web server will translate `+` to space? These conversions are tricky and don't happen in every part of the URL
* I use a GET request to direct the client to Adyen, so I don't have the form problem. However, I think a custom form helper may be a useful feature, but it's not needed for merging this PR.

**Comment by arnoutdemooij** [comment]
Agreed, though I'm not sure about the '+' issue. Can anyone reproduce this problem?

**Comment by mvz** [comment]
I finished my try-out and this branch works well for my use case.

**Comment by mvz** [comment]
> Are we sure the web server will translate + to space?

I checked this, and yes, the `+` is translated into a space in the parameters part of the URL. Next question: Does Adyen properly encode its parameters so that this is not a problem? I would guess yes.

**Comment by mvz** [comment]
The remaining test failures also fail on master. Merging.

**Pull request merged**
