### PR TITLE
Load `refusal_reason` for `BillResponse`

### PR DESCRIPTION
**Pull request by tinogomes**

### CODE REVIEW

**Comment by wvanbergen** [comment]
API specs are failing.

Note: the SOAP API implementation is deprecated, and I am not really accepting any new functionality to it anymore. Ideally this functionality should be ported to the REST API implementation.

Given that the change is small, I am willing to merge this if you get the specs to run again.

**Comment by mvz** [comment]
@tinogomes can you please rebase this on current master? That will probably make the specs green again.

**Comment by tinogomes** [comment]
@mvz @wvanbergen rebased with master

**Comment by mvz** [comment]
Hey @tinogomes, it looks like there are new conflicts due to the other two PRs I merged. Would you mind rebasing again?

**Comment by tinogomes** [comment]
@mvz rebased!

**Comment by mvz** [comment]
@tinogomes it looks like you accidentally checked in `.ruby-gemset` and `.ruby-version`. Can you remove them please?

**Comment by tinogomes** [comment]
@mvz Done and sorry for this mistake.

**Comment by mvz** [comment]
@tinogomes no problem.

**Comment by tinogomes** [comment]
@mvz @wvanbergen when will you ship a new gem version?

**Pull request merged**
